// # CONFIGS
// ## CONST
export const CARD_FLIP_DURATION = 500;
export const CARD_FLIP_BACK_DELAY = 900;
export const MAX_SELECTED_CARDS = 2;
export const GAME_OVER_DURATION = 3000;
export const EXIT_DIALOG_ANIMATION_DURATION = 320;